# Generated by Django 6.0.4 on 2026-04-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_merchant_user'),
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['merchant', 'status'], name='idx_payout_merchant_status'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['merchant', '-created_at'], name='idx_payout_merchant_date'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status', 'processing_at'], name='idx_payout_stale'),
        ),
    ]
