# Generated by Django 6.0.4 on 2026-04-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
        ('merchants', '0002_merchant_user'),
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['merchant', 'entry_type'], name='idx_ledger_merchant_type'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['merchant', '-created_at'], name='idx_ledger_merchant_date'),
        ),
    ]
